version: "3"
services:
  pragma_grafana:
    image: grafana/grafana:5.3.2
    ports:
      - 8000:3000
    volumes:
      - .docker/grafana/grafana.ini:/etc/grafana/grafana.ini
    container_name: pragma-grafana

  pragma_influxdb:
    image: influxdb:1.5.4
    ports:
      - 8086:8086
    volumes:
      - .docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - .docker/finxludb/data:/var/lib/influxdb/data
    container_name: pragma-influxdb
